# -*- coding: utf-8 -*-
"""Smart Attendance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19BcQL0gLEIkhpeGb89oVPT0Xps2k9hD2
"""

!pip install face_recognition
import kagglehub
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime
from google.colab.patches import cv2_imshow

# Download latest version
path = kagglehub.dataset_download("iashiqul/smart-attendance-dataset")
print("Dataset downloaded to:", path)

def markAttendance(name):
    # Create file if it doesn't exist
    if not os.path.exists('Attendance.csv'):
        with open('Attendance.csv', 'w') as f:
            f.writelines('Name,Time,Date')

    with open('Attendance.csv', 'r+') as f:
        myDataList = f.readlines()
        nameList = [line.split(',')[0] for line in myDataList]

        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M:%S')
            dateString = now.strftime('%d-%B-%Y')
            f.writelines(f'\n{name},{dtString},{dateString}')
            print(f"Logged: {name}")

# Test the function
markAttendance('System_Check')

def recognize_and_attend(test_image_path):
    img = cv2.imread(test_image_path)
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    facesCurFrame = face_recognition.face_locations(imgRGB)
    encodesCurFrame = face_recognition.face_encodings(imgRGB, facesCurFrame)

    for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)
        matchIndex = np.argmin(faceDis)

        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            markAttendance(name)

            # Draw rectangle on image for visual feedback
            y1, x2, y2, x1 = faceLoc
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(img, name, (x1+6, y2-6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)

    cv2_imshow(img)

# Replace 'test.jpg' with the filename you uploaded
# recognize_and_attend('test.jpg')

import os
# Check the actual folder structure
print("Contents of the dataset path:")
!ls -R {path} | head -n 20

import os
import cv2
import face_recognition
import numpy as np

# 1. Set the precise path found in your ls -R command
train_path = os.path.join(path, 'Smart attendance dataset/train')

images = []
classNames = []
encodeListKnown = []

print(f"Checking path: {train_path}")

if not os.path.exists(train_path):
    print("Error: Path still not found. Double check the folder names.")
else:
    all_files = os.listdir(train_path)
    print(f"Found {len(all_files)} total files.")

    for img_name in all_files:
        if not img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
            continue

        # 2. Extract name from filename (e.g., 'Abir.6.3051.10.jpg' -> 'Abir')
        student_name = img_name.split('.')[0]

        # To keep it fast, let's only take 3 images per student
        if classNames.count(student_name) >= 3:
            continue

        img_path = os.path.join(train_path, img_name)
        curImg = cv2.imread(img_path)

        if curImg is not None:
            # Convert BGR to RGB
            imgRGB = cv2.cvtColor(curImg, cv2.COLOR_BGR2RGB)

            # Encode
            encodes = face_recognition.face_encodings(imgRGB)
            if len(encodes) > 0:
                encodeListKnown.append(encodes[0])
                classNames.append(student_name)
                print(f"Encoded: {student_name} ({img_name})")

    print(f"\n✅ Encoding Complete!")
    print(f"Total Encodings: {len(encodeListKnown)}")
    print(f"Unique Students: {len(set(classNames))}")

from google.colab import files
uploaded = files.upload()
test_filename = list(uploaded.keys())[0]

import face_recognition
from google.colab.patches import cv2_imshow

# Load the image you just uploaded
test_img = cv2.imread(test_filename)
imgRGB = cv2.cvtColor(test_img, cv2.COLOR_BGR2RGB)

# Find faces in the test image
facesCurFrame = face_recognition.face_locations(imgRGB)
encodesCurFrame = face_recognition.face_encodings(imgRGB, facesCurFrame)

for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
    # Compare with our database
    matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
    faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)

    # Get the best match
    matchIndex = np.argmin(faceDis)

    if matches[matchIndex]:
        name = classNames[matchIndex].upper()
        print(f"✅ Match Found: {name}")
        markAttendance(name) # Automatically logs to Attendance.csv

        # Draw a box and name on the image
        y1, x2, y2, x1 = faceLoc
        cv2.rectangle(test_img, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(test_img, name, (x1, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)
    else:
        print("❌ Unknown Face")

cv2_imshow(test_img)

from google.colab import files
uploaded = files.upload()
test_filename = list(uploaded.keys())[0]

import face_recognition
from google.colab.patches import cv2_imshow

# Load the image you just uploaded
test_img = cv2.imread(test_filename)
imgRGB = cv2.cvtColor(test_img, cv2.COLOR_BGR2RGB)

# Find faces in the test image
facesCurFrame = face_recognition.face_locations(imgRGB)
encodesCurFrame = face_recognition.face_encodings(imgRGB, facesCurFrame)

for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
    # Compare with our database
    matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
    faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)

    # Get the best match
    matchIndex = np.argmin(faceDis)

    if matches[matchIndex]:
        name = classNames[matchIndex].upper()
        print(f"✅ Match Found: {name}")
        markAttendance(name) # Automatically logs to Attendance.csv

        # Draw a box and name on the image
        y1, x2, y2, x1 = faceLoc
        cv2.rectangle(test_img, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(test_img, name, (x1, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)
    else:
        print("❌ Unknown Face")

cv2_imshow(test_img)

from google.colab import files
uploaded = files.upload()
test_filename = list(uploaded.keys())[0]

import face_recognition
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Get the list of all files you just uploaded
uploaded_files = list(uploaded.keys())
print(f"Processing {len(uploaded_files)} images...")

for filename in uploaded_files:
    print(f"\n--- Analyzing {filename} ---")

    # Load image
    test_img = cv2.imread(filename)
    if test_img is None:
        print(f"Skipping {filename}: Could not read file.")
        continue

    imgRGB = cv2.cvtColor(test_img, cv2.COLOR_BGR2RGB)

    # Find faces and encodings in this specific image
    facesCurFrame = face_recognition.face_locations(imgRGB)
    encodesCurFrame = face_recognition.face_encodings(imgRGB, facesCurFrame)

    if not encodesCurFrame:
        print(f"No faces detected in {filename}")
        continue

    for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
        # Compare with your database
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)
        matchIndex = np.argmin(faceDis)

        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(f"✅ Match Found: {name}")
            markAttendance(name) # Logs to CSV

            # Draw visual feedback
            y1, x2, y2, x1 = faceLoc
            cv2.rectangle(test_img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(test_img, name, (x1, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
        else:
            print(f"❌ Unknown Face in {filename}")

    # Show the result for each image
    cv2_imshow(test_img)

print("\nAll images processed! You can now check your Attendance.csv.")

import pandas as pd
from google.colab import files

# Display the log
df = pd.read_csv('Attendance.csv')
print(df.tail(10)) # Show the last 10 entries

# Download the file
files.download('Attendance.csv')

import pandas as pd
from google.colab import files

# Convert CSV to Excel
df = pd.read_csv('Attendance.csv')
df.to_excel('Final_Attendance_Report.xlsx', index=False)

# Download the final report
files.download('Final_Attendance_Report.xlsx')